"""empty message

Revision ID: c94c701b3a28
Revises: fc4a81641b8b
Create Date: 2016-02-29 14:55:17.917074

"""

# revision identifiers, used by Alembic.
revision = 'c94c701b3a28'
down_revision = 'fc4a81641b8b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.drop_column('user', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'username')
    ### end Alembic commands ###
